# Generated by Django 5.0.6 on 2024-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpvalid', '0002_rename_tp_created_at_otptoken_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c06a30', max_length=6),
        ),
        migrations.AlterField(
            model_name='ride',
            name='verification_code',
            field=models.CharField(blank=True, default='a81f0b', max_length=6),
        ),
    ]
