# Generated by Django 5.0.6 on 2024-09-12 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpvalid', '0003_alter_otptoken_otp_code_alter_ride_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='ride',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='e4979f', max_length=6),
        ),
    ]
