# Generated by Django 5.0.6 on 2024-09-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpvalid', '0004_remove_ride_date_remove_ride_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='1ac0c9', max_length=6),
        ),
    ]
