# Generated by Django 5.0.6 on 2024-09-12 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpvalid', '0007_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='drop_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='0e478d', max_length=6),
        ),
    ]
