# Generated by Django 5.0.6 on 2024-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpvalid', '0008_ride_drop_time_ride_pickup_time_ride_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a603ec', max_length=6),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
