# Generated by Django 5.0.6 on 2024-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpvalid', '0009_alter_otptoken_otp_code_alter_ride_pickup_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='b51783', max_length=6),
        ),
    ]
