# Generated by Django 5.0.6 on 2024-09-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpvalid', '0012_ride_date_published_ride_ride_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='5dc556', max_length=6),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
